### ISSUE TITLE
Add support for Clickhouse db

### ISSUE THREAD

**Issue by cortze** [cortze/unit-db-test#4]
# Description
With the heavy migration of GotEth from PSQL to Clickhouse, there is a vast need to update this module to support the Clickhouse driver.

# Tasks:
- [x] Add support for Clickhouse DBs
   - [x] add support for Clickhouse drivers
   - [x] Maintain the SQL driver (make the user choose which one or both to use?)
- [x] Add some DB endpoint benchmarks (Clickhouse vs PSQL endpoints) as Clickhouse offers both, a native Clickhouse connection and a SQL-like endpoint 

I still need to check further how Clickhouse works, but this should be all.

**Comment by cortze** [comment]
Closed with #5
